config/routes.rb
Rails.application.routes.draw do
  # 顧客用
  # skipは不要なルーティングを削除
  # URL /users/sign_in ...
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  # deviseに新たにルーティングを追加（スコープを経由）（ゲストログイン機能）
  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  # 管理者
  # skipは不要なルーティングを削除
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    resources :users, only: [:index, :show, :edit, :update]
    resources :novels, only: [:index, :show, :edit, :update, :destroy] do
      resources :novel_comments, only: [:destroy]
    end
    resources :genres, only: [:index, :show, :edit, :create, :update, :destroy]
    get "search" => "searches#search"
  end

  namespace :public, path: "" do
    get '/' => "homes#top"
    get '/about' => 'homes#about'
    get '/timeline' => 'homes#index'
    get "search" => "searches#search"
    # 退会確認画面
    get '/users/unsubscribe' => 'users#unsubscribe'
    # 論理削除用のルーティング
    patch '/users/withdraw' => 'users#withdraw'
    resources :novels do
      # 1人のユーザーは1つの投稿に対して1回しか良いね出来ない→resourceを使ってURLに[:id]を含めない
      resource :favorites, only: [:create, :destroy]
      resources :novel_comments, only: [:create, :destroy]
      collection do
        get 'confirm'
      end
    end
    resources :users, only: [:index, :show, :edit, :update] do
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'

      member do
        get :favorites
      end
    end
    resources :genres, only: [:index, :create, :show]
    resources :chats, only: [:show, :create]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/admin/searches_controller.rb
class Admin::SearchesController < ApplicationController
  before_action :authenticate_admin!

  def search
    # params[:range]は検索モデル,params[:search]は検索方法,params[:word]は検索ワード
    @range = params[:range]
    @word = params[:word]

    if @range == "会員"
      @users = User.looks(params[:search], params[:word])
    else
      @novels = Novel.looks(params[:search], params[:word])
    end
  end
end

app/helpers/admin/searches_helper.rb
module Admin::SearchesHelper
end

app/views/admin/searches/_search.html.erb
<%= form_with url: admin_search_path, method: :get do |f| %>
  <%= f.text_field :word %>
  <!--複数モデルを検索できるようにする記述-->
  <%= f.select :range, options_for_select([['会員'], ['小説']]) %>
  <%= f.submit "検索", class: "btn btn-sm btn-outline-success" %>
<% end %>

app/views/admin/searches/search.html.erb
<div class="container">
  <div class="row">
    <div class="col-8 offset-2 mt-3">

        <% if @range == "会員" %>
          <h4>会員検索結果 "<%= @word %>"</h4>
          <table class="table table-borderless">
            <tbody>
              <% @users.each do |user| %>
                  <tr>
                    <td>
                      <%= link_to admin_user_path(user), class:"text-success" do %>
                        <%= image_tag user.get_profile_image(50, 50) %>
                      <% end %>
                    </td>
                    <td>
                      <%= link_to admin_user_path(user), class:"text-success" do %>
                        <%= user.name %>
                      <% end %>
                    </td>
                  </tr>
              <% end %>
            </tbody>
          </table>

        <% else %>
          <h4>ゴフノベル検索結果 "<%= @word %>"</h4>
          <table class="table table-borderless">
            <tbody>
              <% @novels.each do |novel| %>
                <tr>
                  <td>
                    <%= link_to admin_novel_path(novel) do %>
                      <%= novel.title %>
                    <% end %>
                  </td>
                  <td>
                    <%= link_to admin_user_path(novel.user), class:"text-success" do %>
                      <%= novel.user.name %>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        <% end %>

    </div>
  </div>
</div>