config/routes.rb
Rails.application.routes.draw do
  # 顧客用
  # skipは不要なルーティングを削除
  # URL /users/sign_in ...
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  # deviseに新たにルーティングを追加（スコープを経由）（ゲストログイン機能）
  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  # 管理者
  # skipは不要なルーティングを削除
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    resources :users, only: [:index, :show, :edit, :update]
    resources :novels, only: [:index, :show, :edit, :update, :destroy] do
      resources :novel_comments, only: [:destroy]
    end
    resources :genres, only: [:index, :show, :edit, :create, :update, :destroy]
    get "search" => "searches#search"
  end

  namespace :public, path: "" do
    get '/' => "homes#top"
    get '/about' => 'homes#about'
    get '/timeline' => 'homes#index'
    get "search" => "searches#search"
    # 退会確認画面
    get '/users/unsubscribe' => 'users#unsubscribe'
    # 論理削除用のルーティング
    patch '/users/withdraw' => 'users#withdraw'
    resources :novels do
      # 1人のユーザーは1つの投稿に対して1回しか良いね出来ない→resourceを使ってURLに[:id]を含めない
      resource :favorites, only: [:create, :destroy]
      resources :novel_comments, only: [:create, :destroy]
      collection do
        get 'confirm'
      end
    end
    resources :users, only: [:index, :show, :edit, :update] do
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'

      member do
        get :favorites
      end
    end
    resources :genres, only: [:index, :create, :show]
    resources :chats, only: [:show, :create]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/novel.rb
class Novel < ApplicationRecord
  belongs_to :user
  belongs_to :genre
  has_many :novel_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  # favoritesテーブルを通ってuserモデルのデータを持ってくる
  has_many :favorited_users, through: :favorites, source: :user
  has_many :view_counts, dependent: :destroy
  has_many :active_favorites, lambda { where(user_id: User.deleted.pluck(:id)) }, class_name: 'Favorite'
  has_many :active_comments, lambda { where(user_id: User.deleted.pluck(:id)) }, class_name: 'NovelComment'

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 3000 }

  enum status: { published: 0, draft: 1 }

  # 退会していない人のいいねだけを抽出するメソッド
  # def active_favorites
  #  favorites.joins(:user).where(user:{ is_deleted: false })
  # end

  # 退会していない人のコメントだけを抽出するメソッド
  # def active_comments
  #  novel_comments.joins(:user).where(user:{ is_deleted: false })
  # end

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  # 検索方法分岐
  def self.looks(search, word)
    @novel = Novel.where("title LIKE? or body LIKE?", "%#{word}%", "%#{word}%")
  end
end

app/controllers/admin/novels_controller.rb
class Admin::NovelsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @novels = Novel.page(params[:page]).per(10)
  end

  def show
    @novel = Novel.find(params[:id])
    @genre = @novel.genre_id
    @user = @novel.user
  end

  def edit
    @novel = Novel.find(params[:id])
    @genres = Genre.all
  end

  def update
    @novel = Novel.find(params[:id])
    if @novel.update(novel_params)
      flash[:notice] = '小説の編集に成功しました'
      redirect_to admin_novel_path(@novel)
    else
      @genres = Genre.all
      flash.now[:alert] = '小説の編集に失敗しました'
      render :edit
    end
  end

  def destroy
    @novel = Novel.find(params[:id])
    @novel.destroy
    flash[:notice] = '小説の削除に成功しました'
    redirect_to admin_novels_path
  end

  private

  def novel_params
    params.require(:novel).permit(:title, :body, :genre_id)
  end
end

app/helpers/admin/novels_helper.rb
module Admin::NovelsHelper
end

app/views/admin/novels/_list.html.erb
<table class="table">
  <thead>
  <tr>
  <th>タイトル</th>
  <th>作家名</th>
  </tr>
  </thead>
  <tbody>
    <% novels.each do |novel| %>
      <tr>
        <td>
          <%= link_to admin_novel_path(novel) do %>
            <%= novel.title %>
          <% end %>
        </td>
        <td>
          <%= link_to admin_user_path(novel.user) do %>
            <%= novel.user.name %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/novels/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col text-center mt-1", style="background-color: #99cccc;">
      <%= flash.now[:alert] %>
      <% if @novel.errors.any? %>
        <%= @novel.errors.count %>件のエラーが発生しました
        <ul style="list-style: none;">
          <% @novel.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-8 offset-2 mt-3">
      <div class="admin-wrapped">
        <h4 style="background-color: #000088;", class="text-white pl-5">小説編集</h4>
        <%= form_with model: @novel, url: admin_novel_path(@novel.id), method: :patch do |f| %>
          <table class="table table-borderless">
            <tr><td><strong>タイトル</strong></td></tr>
            <tr><td><%= f.text_field :title, size: 85 %></td></tr>
            <tr><td><strong>ジャンル</strong></td></tr>
            <tr><td>
              <%= f.collection_select(:genre_id, @genres, :id, :name, prompt: "--選択してください--") %>
            </td></tr>
            <tr><td><strong>小説本文</strong></td></tr>
            <tr><td><%= f.text_area :body, rows: 10, cols: 90 %></td></tr>
            <tr><td><%= f.submit '変更を保存する', class:"btn btn-sm btn-success", data: { confirm: "本当に変更しますか？"} %></td></tr>
          </table>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/novels/index.html.erb
<div class="container">
  <div class="row">
    <div class="col text-center mt-1", style="background-color: #99cccc;">
      <%= flash[:notice] %>
    </div>
  </div>
  <div class="row">
    <div class="col-8 offset-2 mt-3">
      <div class="admin-wrapped">
        <h4 style="background-color: #000088;", class="text-white pl-5">ゴフノベル一覧</h4>

        <%= render 'admin/novels/list', novels: @novels %>
        <%= paginate @novels%>
      </div>
    </div>
  </div>
</div>

app/views/admin/novels/show.html.erb
<div class="container">
  <div class="row">
    <div class="col text-center mt-1", style="background-color: #99cccc;">
      <%= flash[:notice] %>
    </div>
  </div>
  <div class="row">
    <div class="col-8 offset-2 mt-5">
      <div class="admin-wrapped">
        <h4 class="text-center"><%= @novel.title %></h4><br>
        <p class="text-center">
          <%= link_to admin_user_path(@user) do %>
            <%= @novel.user.name %>
          <% end %>
        </p>
        <p class="text-center">
          <%= link_to admin_genre_path(@genre) do%>
            <%= @novel.genre.name %>
          <% end %>
        </p>
        <table class="table table-borderless">
          <tr>
            <td><%= safe_join(@novel.body.split("\n"),tag(:br)) %></td>
          </tr>
          <td>
              コメント件数: <%= @novel.novel_comments.count %>
          </td>
          <tr>
            <td>投稿日: <%= @novel.created_at.strftime('%Y/%m/%d') %></td>
          </tr>
          <tr>
            <td>
              <%= link_to "内容を編集する", edit_admin_novel_path(@novel), class: "btn btn-success ml-2 mr-5" %>
              <%= link_to "小説を削除する", admin_novel_path, method: :delete, class: "btn btn-danger ml-5", data: { confirm: "本当に削除しますか？"} %>
            </td>
          </tr>
        </table>
        <table class="table table-borderless">
          <% @novel.novel_comments.each do |novel_comment| %>
          <tr>
            <td width="10%"><%= image_tag novel_comment.user.get_profile_image(50, 50) %></td>
            <td width="15%"><%= novel_comment.user.name %></td>
            <td width="50%"><%= novel_comment.comment %></td>
            <td width="15%"><%= novel_comment.created_at.strftime('%Y/%m/%d') %></td>
            <td>
              <%= link_to "削除", admin_novel_novel_comment_path(novel_comment.novel, novel_comment), method: :delete, remote: true, class: "text-danger", data: { confirm: "本当に削除しますか？"} %>
            </td>
          </tr>
          <% end %>
        </table>
      </div>
    </div>
  </div>
</div>