config/routes.rb
Rails.application.routes.draw do
  # 顧客用
  # skipは不要なルーティングを削除
  # URL /users/sign_in ...
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  # deviseに新たにルーティングを追加（スコープを経由）（ゲストログイン機能）
  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  # 管理者
  # skipは不要なルーティングを削除
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    resources :users, only: [:index, :show, :edit, :update]
    resources :novels, only: [:index, :show, :edit, :update, :destroy] do
      resources :novel_comments, only: [:destroy]
    end
    resources :genres, only: [:index, :show, :edit, :create, :update, :destroy]
    get "search" => "searches#search"
  end

  namespace :public, path: "" do
    get '/' => "homes#top"
    get '/about' => 'homes#about'
    get '/timeline' => 'homes#index'
    get "search" => "searches#search"
    # 退会確認画面
    get '/users/unsubscribe' => 'users#unsubscribe'
    # 論理削除用のルーティング
    patch '/users/withdraw' => 'users#withdraw'
    resources :novels do
      # 1人のユーザーは1つの投稿に対して1回しか良いね出来ない→resourceを使ってURLに[:id]を含めない
      resource :favorites, only: [:create, :destroy]
      resources :novel_comments, only: [:create, :destroy]
      collection do
        get 'confirm'
      end
    end
    resources :users, only: [:index, :show, :edit, :update] do
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'

      member do
        get :favorites
      end
    end
    resources :genres, only: [:index, :create, :show]
    resources :chats, only: [:show, :create]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :novels, dependent: :destroy
  has_many :novel_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :view_counts, dependent: :destroy
  has_many :user_rooms, dependent: :destroy
  has_many :chats, dependent: :destroy

  # フォローした、されたの関係
  # 「reverse_of_relationships」は「relationships」とごっちゃになるため、わかりやすくするために命名
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy

  # 一覧画面で使う
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower

  scope :deleted, -> { where(is_deleted: false) }

  has_one_attached :profile_image

  validates :name, presence: true, uniqueness: true, length: { minimum: 2, maximum: 20 }
  validates :introduction, length: { maximum: 100 }
  validates :email, uniqueness: true

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  # find_or_create_by!でゲストユーザーがなければ作成、あれば取り出す。
  # ゲストユーザーがないときに作成するユーザー情報を記述
  def self.guest
    find_or_create_by!(name: 'ゲストユーザー', email: 'aaa@aaa.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = 'ゲストユーザー'
    end
  end

  # フォローしたときの処理
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  
  # フォローを外すときの処理
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  
  # フォローしているか判定
  def following?(user)
    followings.include?(user)
  end

  def active_followings
    # is_deletedがfalseの人のidだけを取って来る処理
    # selectメソッドは条件を指定してその条件を満たすものだけを抜き出す
    # {unless~~}は~~がfalseの時だけidを返すようになっている
    followings.select { |following|following unless following.is_deleted }
    # followings.where(is_deleted: false)
  end

  def active_followers
    followers.select { |follower|follower unless follower.is_deleted }
  end

  # 検索方法分岐
  def self.looks(search, word)
    @user = User.where("name LIKE?", "%#{word}%")
  end

  # ログイン時に退会済みのユーザーが同じアカウントでログインできないように制約
  def active_for_authentication?
    super && (is_deleted == false)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @users = User.page(params[:page]).per(10)
  end

  def show
    @user = User.find(params[:id])
    @novels = @user.novels
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "会員情報の編集に成功しました"
      redirect_to admin_user_path(@user)
    else
      flash.now[:alert] = "会員情報の編集に失敗しました"
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :email, :introduction, :is_deleted)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/_error.html.erb
<% if user.errors.any? %>
  <%= user.errors.count %>件のエラーが発生しました
  <ul style="list-style: none;">
    <% user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/admin/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col text-center mt-1", style="background-color: #99cccc;">
      <%= flash.now[:alert] %>
      <%= render 'error', user: @user %>
    </div>
  </div>

  <div class="row">
    <div class="col-8 offset-2">
      <div class="admin-wrapped">
        <h4 style="background-color: #000088;", class="text-white pl-5">会員情報編集</h4>
        <%= form_with model: @user, url: admin_user_path(@user), method: :patch do |f| %>
          <table class="table table-borderless">

            <tr>
              <td><label for="inputName">会員名</label></td>
              <td><%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"ユーザー名" %></td>
            </tr>
            <tr>
              <td><label for="inputImage">プロフィール画像</label></td>
              <td><%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %></td>
            </tr>
            <tr>
              <td><label for="inputIntroduction">自己紹介</label></td>
              <td><%= f.text_area :introduction, autofocus: true, id:"inputIntroduction", placeholder:"自己紹介" %></td>
            </tr>
            <tr>
              <td>会員ステータス</td>
              <td>
                <%= f.radio_button :is_deleted, :true %>
                <%= f.label :is_deleted, "退会" %>
                <%= f.radio_button :is_deleted, :false %>
                <%= f.label :is_deleted, "有効" %>
              </td>
            </tr>
            <tr>
              <td></td>
              <td><%= f.submit "変更を保存", class:"btn btn-sm btn-success", data: { confirm: "本当に変更しますか？"} %></td>
            </tr>

          </table>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col text-center mt-1", style="background-color: #99cccc;">
      <%= flash[:notice] %>
    </div>
  </div>
  <div class="row">
    <div class="col-8 offset-2 mt-3">
      <div class="admin-wrapped">
        <h4 style="background-color: #000088;", class="text-white pl-5">会員一覧</h4>
        <table class="table">
          <thead>
            <tr>
              <th>会員ID</th>
              <th>会員名</th>
              <th>メールアドレス</th>
              <th>ステータス</th>
            </tr>
          </thead>
          <% @users.each do |user| %>
            <tbody>
              <tr>
                <td><%= user.id %></td>
                <td>
                  <%= link_to admin_user_path(user) do %>
                    <%= user.name %>
                  <% end %>
                </td>
                <td><%= user.email %></td>
                <td>
                  <% if user.is_deleted == true %>
                    <p>退会</p>
                  <% else %>
                    <p>有効</p>
                  <% end %>
                </td>
              </tr>
            </tbody>
          <% end %>
        </table>
        <%= paginate @users %>
      </div>
    </div>
  </div>
</div>

app/views/admin/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col text-center mt-1", style="background-color: #99cccc;">
      <%= flash[:notice] %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-8 offset-2 mt-3">
      <h4 style="background-color: #000088;", class="text-white pl-5"><%= @user.name %>さんのプロフィール詳細</h4>
      <p><%= image_tag @user.get_profile_image(100, 100) %></p>
    </div>
  </div>
  <div class="row">
    <div class="col-md-8 offset-2">
      <table class="table table-borderless">
        <tr>
          <td>会員ID</td>
          <td><%= @user.id %></td>
        </tr>
        <tr>
          <td>会員名</td>
          <td><%= @user.name %></td>
        </tr>
        <tr>
          <td>自己紹介</td>
          <td><%= @user.introduction %></td>
        </tr>
        <tr>
          <td>会員ステータス</td>
          <td>
            <% if @user.is_deleted == true %>
              <p>退会済み</p>
            <% else %>
              <p>有効</p>
            <% end %>
          </td>
        </tr>
      </table>
      <div class="admin-wrapped">
      <h5 style="background-color: #000088;", class="text-white pl-5">投稿したゴフノベル</h5>
        <table class="table">
          <thead>
            <th>タイトル</th>
            <th>投稿日</th>
          </thead>
          <% @novels&.each do |novel| %>
            <tbody>
              <tr>
                <td>
                  <%= link_to admin_novel_path(novel) do %>
                    <%= novel.title %>
                  <% end %>
                </td>
                <td><%= novel.created_at.strftime('%Y/%m/%d') %></td>
              </tr>
            </tbody>
          <% end%>
        </table>
      </div>
      <%= link_to "編集する", edit_admin_user_path(@user), class: "btn btn-success" %>
      <%= link_to "会員一覧へ", admin_users_path, class: "btn btn-secondary" %>
    </div>
  </div>
</div>