config/routes.rb
Rails.application.routes.draw do
  # 顧客用
  # skipは不要なルーティングを削除
  # URL /users/sign_in ...
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  # deviseに新たにルーティングを追加（スコープを経由）（ゲストログイン機能）
  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  # 管理者
  # skipは不要なルーティングを削除
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    resources :users, only: [:index, :show, :edit, :update]
    resources :novels, only: [:index, :show, :edit, :update, :destroy] do
      resources :novel_comments, only: [:destroy]
    end
    resources :genres, only: [:index, :show, :edit, :create, :update, :destroy]
    get "search" => "searches#search"
  end

  namespace :public, path: "" do
    get '/' => "homes#top"
    get '/about' => 'homes#about'
    get '/timeline' => 'homes#index'
    get "search" => "searches#search"
    # 退会確認画面
    get '/users/unsubscribe' => 'users#unsubscribe'
    # 論理削除用のルーティング
    patch '/users/withdraw' => 'users#withdraw'
    resources :novels do
      # 1人のユーザーは1つの投稿に対して1回しか良いね出来ない→resourceを使ってURLに[:id]を含めない
      resource :favorites, only: [:create, :destroy]
      resources :novel_comments, only: [:create, :destroy]
      collection do
        get 'confirm'
      end
    end
    resources :users, only: [:index, :show, :edit, :update] do
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'

      member do
        get :favorites
      end
    end
    resources :genres, only: [:index, :create, :show]
    resources :chats, only: [:show, :create]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
    <footer class="bg-light text-white pt-5 pb-4" style="background-color: rgba(240,255,240);">
      <div class="container">
        <div class="row no-gutters">
          <div class="col text-center">
            <a href="/">
              <%= image_tag 'logo.jpg' %>
              <%= link_to new_admin_session_path do %>
                <i class="fas fa-feather text-info"></i>
              <% end %>
            </a>
          </div>
        </div>
      </div>
    </footer>
  </body>

app/views/layouts/_header.html.erb
<header class="shadow-sm">
  <!--<nav class="navbar navbar-expand-lg navbar-light border-bottom border-success" style="background-color: rgba(240,255,240);">-->
  <nav class="navbar navbar-expand-lg navbar-light border-bottom border-success">
    <div class="container">
      <a class="navbar-brand p-3" href="/"><span><%= image_tag 'logo.jpg' %><i class="fas fa-feather text-info"></i></span></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                    aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
          <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to public_user_path(current_user.id), class: 'nav-link text-success' do %>
                <i class="fas fa-address-book"></i><br>
                マイページ
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to public_timeline_path, class: 'nav-link text-success' do %>
                <i class="fas fa-home"></i><br>
                タイムライン
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to public_users_path, class: 'nav-link text-success' do %>
                <i class="fas fa-user"></i><br>
                会員一覧
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to public_novels_path, class: 'nav-link text-success' do %>
                <i class="fas fa-book"></i><br>
                ゴフノベル<br>一覧
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to public_genres_path, class: 'nav-link text-success' do %>
                <i class="fas fa-link"></i><br>
                ジャンル<br>一覧
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-success' do %>
                <i class="fas fa-sign-out-alt"></i><br>
                ログアウト
              <% end %>
            </li>
            <li class="nav-item">
              <%= render 'public/searches/search' %>
            </li>
          <% elsif admin_signed_in? %>
            <li class="nav-item">
              <%= link_to admin_users_path, class: 'nav-link text-success' do %>
                <i class="fas fa-user"></i>
                会員一覧
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to admin_novels_path, class: 'nav-link text-success' do %>
                <i class="fas fa-book"></i>
                ゴフノベル一覧
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to admin_genres_path, class: 'nav-link text-success' do %>
                <i class="fas fa-link"></i>
                ジャンル一覧
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to destroy_admin_session_path, method: :delete, class: 'nav-link text-success' do %>
                <i class="fas fa-sign-out-alt"></i>
                ログアウト
              <% end %>
            </li>
            <li class="nav-item">
              <%= render 'admin/searches/search' %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to public_path, class: 'nav-link text-success' do %>
                <i class="fas fa-home"></i>
                ホーム
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to public_about_path, class: 'nav-link text-success' do %>
                <i class="fas fa-book-open"></i>
                5HUNOVELとは
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_user_registration_path, class: 'nav-link text-success' do %>
                <i class="fas fa-user-plus"></i>
                会員登録
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_user_session_path, class: 'nav-link text-success' do %>
                <i class="fas fa-sign-in-alt"></i>
                ログイン
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NOVEL</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body class="d-flex flex-column vh-100">
    <%= render 'layouts/header' %>
    <main class="mb-auto">
    <%= yield %>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>